### ISSUE TITLE
Failed at phantomjs@1.9.9 install script

### ISSUE THREAD

**Issue by darrenjsmith** [dfischer/meteor-phantomjs#6]
Hey-
I'm trying to deploy to modulus and receiving the following error.
Specifically the bit that says:

```
npm ERR! Failed at the phantomjs@1.9.9 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
```

I have both spiderable and this package installed.. Any ideas? Hope someone can help! :) 

Full Log:

```
phantomjs@1.9.9 install /mnt/data/1/node_modules/phantomjs
node install.js

module.js:340
    throw err;
          ^
Error: Cannot find module './util'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/mnt/data/1/node_modules/adm-zip/zipEntry.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! phantomjs@1.9.9 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.9 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-36-generic
npm ERR! command "/mnt/nave/installed/0.10.34/bin/node" "/mnt/nave/installed/0.10.34/bin/npm" "install" "--production" "--registry" "http://registry.npmjs.org" "--cache" "/mnt/data/.npm"
npm ERR! cwd /mnt/data/1
npm ERR! node -v v0.10.34
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
INFO: Main file specified in package.json: main.js
INFO: Starting application.
```

**Comment by bstocks** [comment]
I had this same issue. I ran `npm update -g modulus` to get the latest modulus CLI and then tried again and it worked.... not sure if there were other factors at play, but worth a try.
